// Step 1. Import the 'mysql2' and 'dotenv' packages.
import {createConnection} from "mysql2/promise";
import dotenv from "dotenv";
import * as fs from "fs";

/**
 * Database connection.
 * @typedef {import("mysql2/promise").Connection} Connection
 */

/**
 * Player.
 * @typedef {Object} Player
 * @property {number} id Player ID.
 * @property {number} coins Coins.
 * @property {number} goods Goods.
 */

// Step 2. Load environment variables from .env file via the 'dotenv' package.
dotenv.config();

/**
 * 🔌 Step 3 (Option 1). Establish a connection to TiDB cluster with connection URL.
 *
 * @returns {Promise<Connection>}
 */
async function connectWithURL() {
    try {
        const url = process.env.DATABASE_URL || 'mysql://root@localhost:4000/test';
        return await createConnection(url);
    } catch (err) {
        throw new Error(`Failed to connect to TiDB cluster: ${err.message}`);
    }
}

/**
 * 🔌 Step 3 (Option 2). Establish a connection to TiDB cluster with connection options.
 *
 * @returns {Promise<Connection>}
 */
async function connectWithOptions() {
    try {
        const options = {
            host: process.env.TIDB_HOST || '127.0.0.1',
            port: process.env.TIDB_PORT || 4000,
            user: process.env.TIDB_USER || 'root',
            password: process.env.TIDB_PASSWORD || '',
            database: process.env.TIDB_DATABASE || 'test',
            ssl: process.env.TIDB_ENABLE_SSL === 'true' ? {
                minVersion: 'TLSv1.2',
                ca: process.env.TIDB_CA_PATH ? fs.readFileSync(process.env.TIDB_CA_PATH) : undefined
            } : null,
        }
        return await createConnection(options);
    } catch (err) {
        throw new Error(`Failed to connect to TiDB cluster: ${err.message}`);
    }
}

/**
 * Get TiDB version.
 *
 * @param conn {Connection}
 * @returns {Promise<string>}
 */
async function getTiDBVersion(conn) {
    const [rows] = await conn.query('SELECT VERSION() AS tidb_version;');
    return rows[0]['tidb_version'];
}

/**
 * Load sample game data.
 *
 * @param conn {Connection}
 * @returns {Promise<void>}
 */
async function loadSampleGameData(conn) {
    const content = fs.readFileSync('sql/game.init.sql', 'utf8');
    const sqls = content.split(';');
    for (const sql of sqls) {
        if (sql.trim() === '') {
            continue;
        }
        await conn.query(sql);
    }
}

/**
 * 🆕 CREATE a new player.
 *
 * @param conn {Connection} Database connection.
 * @param coins {number} Initial coins.
 * @param goods {number} Initial goods.
 * @returns {Promise<number>} The ID auto-generated by TiDB for the new player.
 */
async function createPlayer(conn, coins, goods) {
    const [rsh] = await conn.query(
        'INSERT INTO players (coins, goods) VALUES (?, ?);',
        [coins, goods]
    );
    return rsh.insertId;
}

/**
 * ℹ️ READ player information by ID.
 *
 * @param conn {Connection} Database connection.
 * @param id {number} The ID of the player to get.
 * @returns {Promise<Player>}
 */
async function getPlayerByID(conn, id) {
    const [rows] = await conn.query(
        'SELECT id, coins, goods FROM players WHERE id = ?;',
        [id]
    );
    return rows[0];
}

/**
 * 🔢 UPDATE player.
 *
 * @param conn {Connection} Database connection.
 * @param playerID {number} The ID of the player to update.
 * @param incCoins {number} The increased coins.
 * @param incGoods {number} The increased goods.
 * @returns {Promise<number>} The number of affected rows, return 1 if updated successfully.
 */
async function updatePlayer(conn, playerID, incCoins, incGoods) {
    const [rsh] = await conn.query(
        'UPDATE players SET coins = coins + ?, goods = goods + ? WHERE id = ?;',
        [incCoins, incGoods, playerID]
    );
    return rsh.affectedRows;
}

/**
 * 🚮 DELETE player by ID.
 *
 * @param conn {Connection} Database connection.
 * @param id {number} The ID of the player to delete.
 * @returns {Promise<number>} The number of affected rows, return 1 if deleted successfully.
 */
async function deletePlayerByID(conn, id) {
    const [rsh] = await conn.query(
        'DELETE FROM players WHERE id = ?;',
        [id]
    );
    return rsh.affectedRows;
}

/**
 * 🚪Main function.
 * @returns {Promise<void>}
 */
async function main() {
    let conn = process.env.DATABASE_URL ? await connectWithURL() : await connectWithOptions();
    try {
        const version = await getTiDBVersion(conn);
        console.log(`🔌 Connected to TiDB cluster! (TiDB version: ${version})`);

        console.log('⏳  Loading sample game data...');
        await loadSampleGameData(conn);
        console.log('✅  Loaded sample game data.\n');

        const newPlayer = await createPlayer(conn, 100, 100);
        console.log(`🆕 Created a new player with ID ${newPlayer}.`);

        const player = await getPlayerByID(conn, newPlayer);
        console.log(`ℹ️ Got Player ${player.id}: Player { id: ${player.id}, coins: ${player.coins}, goods: ${player.goods} }`);

        const updatedRows = await updatePlayer(conn, player.id, 50, 50);
        console.log(`🔢 Added 50 coins and 50 goods to player ${player.id}, updated ${updatedRows} row.`);

        const deletedRows = await deletePlayerByID(conn, player.id);
        console.log(`🚮 Deleted ${deletedRows} player data.`);
    } finally {
        // Step 4. Close the connection.
        await conn.end();
    }
}

void main();


